apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict
  namespace: w2511
spec:
  selector:
    matchLabels:
      app: predict
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
      - name: predict
        imagePullPolicy: IfNotPresent
        image: wolu0901/w251-project-predict
