apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: w2511
  labels:
    run: mosquitto
spec:
  type: NodePort
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
    nodePort: 30001
  selector:
    app: mosquitto